services:
  - type: web
    name: slope-stability-analysis
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -e .
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production 